apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: zunaied/api:v4
          ports:
            - containerPort: 5500
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: WEATHER_API_KEY